# Generated by Django 3.1.7 on 2021-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appotests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='test',
            field=models.CharField(choices=[('blood_count', 'blood_count'), ('biopsy', 'biopsy'), ('ecg', 'ecg'), ('ct_scan', 'ct_scan'), ('angiogram', 'angiogram'), ('ultra_sound', 'ultra_sound')], default='', max_length=50),
        ),
    ]
